# Basic
title: 寇少
subtitle: 个人博客
description: 程序员，喜欢打麻将，偶尔写代码.
# 头像里面的标题
avatarTitle: KOUSHAO
# 头像里面的描述
avatarDesc: 算法 / 机器学习
url: "http://kousw.com"



# Comment
comment:
    # disqus: koushao
    duoshuo: koushao

# Social
social:
    qq: 787063665 
    github: shaohuacheng
    mail: kou_sw@163.com

# 百度统计 
# 使用博客模板请去掉或者更换 id 
baidu:
    id: 957e77e1acf1af070570eaad681b4bcb
          

# Google Analytics
# 使用博客模板请去掉或者更换 id
ga:
    id: UA-89438027-1   
    host: auto  


# 《----------------- 上面的信息修改成你自己的 ---------------------------》
#
#
#  _post/ 下的文章更换成你自己的文章
#  帮忙star一下，感谢~????地址： https://github.com/shaohuacheng/shaohuacheng.github.io
#
#
# 《--------------- 下面的信息可以自行选择是否修改 ------------------------》


permalink: /:year/:month/:title/
# Format
markdown: kramdown
highlighter: pygments

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: clear

# The blog button should not be removed.
blog_button:
    title: 博客主页

# Navigation buttons in the front page.s
nav:
    - {title: 所有文章, description: archive, url: '/archive'}   
    - {title: 标签, description: tags, url: '/tags'}      
    - {title: 随笔, description: essay, url: '/essay'}      
    - {title: 关于我, description: about, url: '/about'}      
    

# Pagination
gems: [jekyll-paginate,jekyll-sitemap]
paginate: 20
paginate_path: "page/:num/"

